import assert from 'node:assert/strict';
import {chromium} from 'playwright';
import {checkUpload} from './upload-check.mjs';
const browser=await chromium.launch({channel:'chrome',headless:true});
try{for(const [name,port] of [['next',41791],['nuxt',41792],['angular',41793]]){
 if(process.argv[2]&&name!==process.argv[2])continue;
 const url=`http://127.0.0.1:${port}`;
 const response=await fetch(url),html=await response.text();assert.equal(response.status,200);assert.match(html,/<au-rating[^>]*name="review"/);assert.match(html,/<au-rating[^>]*value="1"/);
 assert.match(html,/<au-pagination[^>]*data-current-page="2"/);
 assert.match(html,/<au-dropdown[^>]*data-text-trigger="Document actions"/);
 assert.match(html,/<au-tree[\s>]/);
 assert.match(html,/<au-accordion-item[^>]*id="ssr-accordion-item"/);
 assert.match(html,/id="ssr-accordion-content"/);
 assert.match(html,/<au-carousel[\s>]/);assert.match(html,/id="ssr-slide-first"/);
 assert.match(html,/<au-card[\s>]/);assert.match(html,/id="ssr-card-heading"/);
 assert.match(html,/<au-breadcrumbs[^>]*items="/);assert.match(html,/id="ssr-crumb-icon"/);
 assert.match(html,/<au-file-upload[^>]*name="attachments"/);
 const noJS=await browser.newPage({javaScriptEnabled:false});
 try {
  await noJS.goto(url);
  assert.deepEqual(await noJS.locator('au-breadcrumbs').evaluate(c=>JSON.parse(c.getAttribute('items'))),[{text:'Home',url:'#crumb-home'},{text:'Guides',url:'#crumb-guides'},{text:'Current page'}]);
  assert.equal(await noJS.locator('au-breadcrumbs').evaluate(c=>c.shadowRoot===null),true);
  assert.equal(await noJS.locator('#ssr-crumb-icon').textContent(),'⌂');
  assert.equal(await noJS.locator('au-file-upload').evaluate(c=>c.shadowRoot===null),true);
  assert.equal(await noJS.locator('#ssr-upload-trigger').textContent(),'Choose attachments');
 } finally {await noJS.close();}
 assert.match(html,/<au-dropdown-item[^>]*id="ssr-action-save"[^>]*value="save"/);
 const page=await browser.newPage();
 // Playwright enables file-chooser interception asynchronously when the first
 // listener is added; registering it at page creation keeps the later upload
 // keypress from racing that setup (the chooser otherwise goes uncaptured).
 page.on('filechooser',()=>{});
 const errors=[];page.on('pageerror',e=>errors.push(String(e)));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
 assert.match(html,/<au-input[^>]*name="text"/);assert.match(html,/<au-input[^>]*value="Initial"/);
 assert.match(html,/<au-textarea[^>]*name="notes"/);assert.match(html,/<au-textarea[^>]*value="Initial notes"/);
 assert.match(html,/<au-checkbox[^>]*name="choice"/);assert.match(html,/<au-switch[^>]*name="enabled"/);
 assert.match(html,/<au-radio-group[^>]*value="standard"/);
 assert.match(html,/<au-tabs[^>]*selected-index="1"/);assert.match(html,/id="ssr-panel-first"/);
 await page.addInitScript(()=>{
  window.ssrElements={};window.ssrTabPanels={};window.ssrActions={};window.ssrAccordion={};window.ssrSlides={};window.ssrCard={};
  window.ssrUpload={};
  const tags=['au-rating','au-input','au-textarea','au-checkbox','au-switch','au-radio-group','au-tabs','au-pagination','au-dropdown','au-tree','au-accordion','au-carousel','au-card','au-breadcrumbs','au-file-upload'];
  const observer=new MutationObserver(()=>{
   for(const tag of tags){const element=document.querySelector(tag);if(element&&!window.ssrElements[tag])window.ssrElements[tag]=element;}
   for(const id of ['ssr-panel-first','ssr-panel-second']){const panel=document.getElementById(id);if(panel&&!window.ssrTabPanels[id])window.ssrTabPanels[id]=panel;}
   for(const id of ['ssr-action-edit','ssr-action-save']){const item=document.getElementById(id);if(item&&!window.ssrActions[id])window.ssrActions[id]=item;}
   for(const id of ['ssr-accordion-item','ssr-accordion-heading','ssr-accordion-content']){const item=document.getElementById(id);if(item&&!window.ssrAccordion[id])window.ssrAccordion[id]=item;}
   for(const id of ['ssr-slide-first','ssr-slide-second']){const item=document.getElementById(id);if(item&&!window.ssrSlides[id])window.ssrSlides[id]=item;}
   for(const id of ['ssr-card-heading','ssr-card-content','ssr-card-footer']){const item=document.getElementById(id);if(item&&!window.ssrCard[id])window.ssrCard[id]=item;}
   const icon=document.getElementById('ssr-crumb-icon');if(icon&&!window.ssrCrumbIcon)window.ssrCrumbIcon=icon;
   for(const id of ['ssr-upload-trigger','ssr-upload-hint']){const node=document.getElementById(id);if(node&&!window.ssrUpload[id])window.ssrUpload[id]=node;}
   if(tags.every(tag=>window.ssrElements[tag])&&Object.keys(window.ssrUpload).length===2&&window.ssrCrumbIcon&&Object.keys(window.ssrTabPanels).length===2&&Object.keys(window.ssrActions).length===2&&Object.keys(window.ssrAccordion).length===3&&Object.keys(window.ssrSlides).length===2&&Object.keys(window.ssrCard).length===3)observer.disconnect();
  });observer.observe(document,{childList:true,subtree:true});
 });
 await page.goto(url);await page.waitForFunction(()=>document.querySelector('au-rating')?.shadowRoot?.querySelector('input:checked')?.value==='1'&&document.querySelector('#ready')?.textContent==='true');
 if(name==='angular')await page.waitForFunction(()=>window.hydrated===true);
 assert.equal(await page.evaluate(()=>document.characterSet),'UTF-8');
 assert.equal(await page.locator('#ssr-crumb-icon').textContent(),'⌂');
 assert.equal(await page.evaluate(()=>Object.entries(window.ssrElements).length===15&&Object.entries(window.ssrElements).every(([tag,element])=>element===document.querySelector(tag))),true);
 assert.equal(await page.evaluate(()=>Object.entries(window.ssrCard).length===3&&Object.entries(window.ssrCard).every(([id,element])=>element===document.getElementById(id))),true);
 assert.equal(await page.evaluate(()=>Object.entries(window.ssrSlides).length===2&&Object.entries(window.ssrSlides).every(([id,element])=>element===document.getElementById(id))),true);
 assert.equal(await page.evaluate(()=>Object.entries(window.ssrAccordion).length===3&&Object.entries(window.ssrAccordion).every(([id,element])=>element===document.getElementById(id))),true);
 assert.equal(await page.evaluate(()=>Object.entries(window.ssrActions).length===2&&Object.entries(window.ssrActions).every(([id,element])=>element===document.getElementById(id))),true);
 assert.equal(await page.evaluate(()=>Object.entries(window.ssrTabPanels).length===2&&Object.entries(window.ssrTabPanels).every(([id,element])=>element===document.getElementById(id))),true);
 assert.equal(await page.evaluate(()=>new FormData(document.querySelector('#controls-form')).has('choice')),false);
 assert.equal(await page.evaluate(()=>new FormData(document.querySelector('#controls-form')).has('enabled')),false);
 await page.click('#update');await page.waitForFunction(()=>document.querySelector('au-rating')?.shadowRoot?.querySelector('input:checked')?.value==='4');
 assert.equal(await page.evaluate(()=>new FormData(document.querySelector('#controls-form')).get('updated')),'4');
 await page.locator('au-rating input:checked').focus();await page.keyboard.press('ArrowLeft');await page.waitForFunction(()=>document.querySelector('#events').textContent==='1');
 assert.equal(await page.evaluate(()=>new FormData(document.querySelector('#controls-form')).get('updated')),'3');
 await page.waitForFunction(()=>document.querySelector('au-input')?.value==='Changed');
 await page.locator('au-input input').focus();await page.keyboard.press('End');await page.keyboard.press('x');
 await page.waitForFunction(()=>document.querySelector('#input-events').textContent==='1');
 assert.equal(await page.evaluate(()=>new FormData(document.querySelector('#controls-form')).get('text')),'Changedx');
 const cdp=await page.context().newCDPSession(page);const ax=await cdp.send('Accessibility.getFullAXTree');const textbox=ax.nodes.find(n=>n.role?.value==='textbox'&&n.name?.value==='Review text');assert.equal(textbox.name.value,'Review text');assert.equal(textbox.description.value,'Enter a review');
 await page.waitForFunction(()=>document.querySelector('au-textarea')?.value==='Changed notes');
 await page.locator('au-textarea textarea').focus();await page.keyboard.press('End');await page.keyboard.press('Enter');await page.keyboard.press('x');
 await page.waitForFunction(()=>document.querySelector('#notes-events').textContent==='2');
 assert.equal(await page.locator('#notes-model').textContent(),'Changed notes\nx');
 assert.equal(await page.evaluate(()=>new FormData(document.querySelector('#controls-form')).get('notes')),'Changed notes\nx');
 const notesAX=await cdp.send('Accessibility.getFullAXTree');const notesBox=notesAX.nodes.find(n=>n.role?.value==='textbox'&&n.name?.value==='Review notes');
 assert.equal(notesBox.description.value,'Enter detailed notes');
 await page.click('#toggle-update');await page.waitForFunction(()=>document.querySelector('au-checkbox').checked&&document.querySelector('au-switch').checked);
 const togglesAX=await cdp.send('Accessibility.getFullAXTree');
 for(const [tag,field,role,label] of [['au-checkbox','choice','checkbox','Receive news'],['au-switch','enabled','switch','Enable notifications']]){
  assert.equal(await page.evaluate(field=>new FormData(document.querySelector('#controls-form')).get(field),field),'on');
  const node=togglesAX.nodes.find(n=>n.role?.value===role&&n.name?.value===label);assert.equal(node.description.value,'Optional preference');
  assert.equal(node.properties.find(p=>p.name==='checked').value.value,'true');
  await page.locator(`${tag} input`).focus();await page.keyboard.press('Space');
  assert.equal(await page.evaluate(field=>new FormData(document.querySelector('#controls-form')).has(field),field),false);
 }
 await page.waitForFunction(()=>document.querySelector('#toggle-events').textContent==='2');
 assert.equal(await page.locator('#toggle-model').textContent(),'false,false');
 await page.waitForFunction(()=>document.querySelector('au-radio-group').value==='standard');
 await page.click('#radio-update');await page.waitForFunction(()=>document.querySelector('au-radio-group').value==='express');
 await page.locator('au-radio-group input:checked').focus();
 await page.evaluate(()=>{window.radioInput=document.querySelector('au-radio-group').shadowRoot.activeElement;document.querySelector('#radio-label-update').click();});
 await page.waitForFunction(()=>document.querySelector('au-radio-group').shadowRoot.querySelectorAll('.text')[1].textContent==='快遞');
 assert.equal(await page.evaluate(()=>document.querySelector('au-radio-group').shadowRoot.activeElement===window.radioInput),true);
 for(const disabled of [true,false]){
  await page.click('#radio-disable');await page.waitForFunction(disabled=>document.querySelector('au-radio-group').disabled===disabled,disabled);
  assert.equal(await page.evaluate(()=>document.querySelector('au-radio-group').value),'express');
  assert.equal(await page.evaluate(()=>new FormData(document.querySelector('#controls-form')).has('delivery')),!disabled);
 }
 const radioAX=await cdp.send('Accessibility.getFullAXTree');const group=radioAX.nodes.find(n=>n.role?.value==='radiogroup'&&n.name?.value==='Delivery');
 assert.equal(group.description.value,'Choose one delivery option');
 await page.locator('au-radio-group input:checked').focus();await page.keyboard.press('ArrowRight');
 await page.waitForFunction(()=>document.querySelector('#radio-events').textContent==='1');
 assert.equal(await page.locator('#radio-model').textContent(),'standard');
 assert.equal(await page.evaluate(()=>new FormData(document.querySelector('#controls-form')).get('delivery')),'standard');
 await page.waitForFunction(()=>document.querySelector('au-tabs').selectedIndex===1);
 await page.locator('au-tabs [role=tab][aria-selected=true]').focus();
 await page.evaluate(()=>{window.tabButton=document.querySelector('au-tabs').shadowRoot.activeElement;document.querySelector('#tab-label-update').click();});
 await page.waitForFunction(()=>document.querySelector('au-tabs').shadowRoot.querySelectorAll('.label')[1].textContent==='細節');
 assert.equal(await page.evaluate(()=>document.querySelector('au-tabs').shadowRoot.activeElement===window.tabButton),true);
 assert.equal(await page.locator('au-tabs [role=tab] .label').nth(1).getAttribute('lang'),'zh-Hant');
 await page.keyboard.press('ArrowLeft');await page.waitForFunction(()=>document.querySelector('#tab-events').textContent==='1');
 assert.equal(await page.locator('#tab-model').textContent(),'0');await page.keyboard.press('Tab');
 assert.equal(await page.evaluate(()=>document.activeElement.id),'ssr-panel-first');
 await page.click('#tab-update');await page.waitForFunction(()=>document.querySelector('au-tabs').selectedIndex===1);
 assert.equal(await page.locator('#tab-events').textContent(),'1');assert.equal(await page.evaluate(()=>document.activeElement.id),'tab-update');
 const tabsAX=await cdp.send('Accessibility.getFullAXTree');const tablist=tabsAX.nodes.find(n=>n.role?.value==='tablist');assert.equal(tablist.name.value,'Review sections');
 const activeTab=tabsAX.nodes.find(n=>n.role?.value==='tab'&&n.name?.value==='細節');const activePanel=tabsAX.nodes.find(n=>n.role?.value==='tabpanel'&&n.name?.value==='細節');
 assert.ok(activeTab.properties.find(p=>p.name==='controls').value.relatedNodes.some(n=>n.backendDOMNodeId===activePanel.backendDOMNodeId));
 await page.waitForFunction(()=>document.querySelector('au-pagination')?.shadowRoot?.querySelector('[aria-current="page"]')?.textContent==='2');
 await page.click('#page-update'); await page.waitForFunction(()=>document.querySelector('au-pagination').currentPage===4);
 assert.equal(await page.locator('#page-events').textContent(),'0,0');
 const next=page.locator('au-pagination [data-control="next"]'); await next.focus();
 await page.evaluate(()=>{window.pageNext=document.querySelector('au-pagination').shadowRoot.activeElement;document.querySelector('#page-label-update').click();});
 await page.waitForFunction(()=>document.querySelector('au-pagination').shadowRoot.querySelector('[data-control="next"]').textContent==='下一頁');
 assert.equal(await page.evaluate(()=>document.querySelector('au-pagination').shadowRoot.activeElement===window.pageNext),true);
 await page.keyboard.press('Enter'); await page.waitForFunction(()=>document.querySelector('#page-model').textContent==='5,10');
 assert.equal(await page.locator('#page-events').textContent(),'1,0');
 assert.equal(await page.evaluate(()=>document.querySelector('au-pagination').shadowRoot.activeElement===window.pageNext),true);
 await page.locator('au-pagination select').focus(); await page.locator('au-pagination select').selectOption('50');
 await page.waitForFunction(()=>document.querySelector('#page-model').textContent==='1,50');
 assert.equal(await page.locator('#page-events').textContent(),'1,1');
 assert.equal(await page.evaluate(()=>document.querySelector('au-pagination').shadowRoot.activeElement.tagName),'SELECT');
 const paginationAX=await cdp.send('Accessibility.getFullAXTree');
 assert.ok(paginationAX.nodes.find(n=>n.role?.value==='combobox'&&n.name?.value==='each page Page size'));
 await page.waitForFunction(()=>document.querySelector('au-dropdown')?.trigger);
 await page.locator('au-dropdown button').focus();await page.keyboard.press('ArrowUp');
 await page.waitForFunction(()=>document.getElementById('ssr-action-save').shadowRoot.activeElement);
 await page.evaluate(()=>{window.actionNode=document.getElementById('ssr-action-save').item;document.getElementById('action-translate').click();});
 await page.waitForFunction(()=>document.getElementById('ssr-action-save').textContent==='儲存'&&document.getElementById('ssr-action-save').getAttribute('value')==='save-copy');
 assert.equal(await page.evaluate(()=>document.getElementById('ssr-action-save').shadowRoot.activeElement===window.actionNode),true);
 assert.equal(await page.locator('#action-events').textContent(),'0');
 const menuAX=await cdp.send('Accessibility.getFullAXTree');
 assert.ok(menuAX.nodes.find(n=>n.role?.value==='menu'&&n.name?.value==='文件操作'));
 assert.ok(menuAX.nodes.find(n=>n.role?.value==='menuitem'&&n.name?.value==='儲存'));
 await page.keyboard.press('Enter');await page.waitForFunction(()=>document.getElementById('action-events').textContent==='1');
 assert.equal(await page.locator('#action-model').textContent(),'save-copy');
 await page.waitForFunction(()=>document.querySelector('au-dropdown').shadowRoot.activeElement===document.querySelector('au-dropdown').trigger);
 await page.evaluate(()=>{const dd=document.querySelector('au-dropdown');const item=document.getElementById('ssr-action-save');item.remove();dd.append(item);dd.trigger.focus();});
 await page.keyboard.press('ArrowUp');await page.waitForFunction(()=>document.getElementById('ssr-action-save').shadowRoot.activeElement);
 await page.keyboard.press('Space');await page.waitForFunction(()=>document.getElementById('action-events').textContent==='2');
 assert.equal(await page.locator('#action-model').textContent(),'save-copy');
 await page.waitForFunction(()=>document.querySelector('au-tree')?.getAllNodes?.().length===4);
 await page.evaluate(()=>document.querySelector('au-tree').focus());await page.keyboard.press('ArrowRight');await page.keyboard.press('ArrowRight');await page.keyboard.press('Space');
 await page.waitForFunction(()=>document.getElementById('tree-events').textContent==='1');
 assert.equal(await page.locator('#tree-model').textContent(),'alpha');
 await page.evaluate(()=>{window.treeAlpha=document.querySelector('au-tree').getAllNodes()[1];document.getElementById('tree-translate').click();});
 await page.waitForFunction(()=>document.querySelector('au-tree').getAllNodes()[1].label==='甲');
 assert.equal(await page.evaluate(()=>{const tree=document.querySelector('au-tree');return tree.getAllNodes()[1]===window.treeAlpha&&tree.findActiveNode().activeNode===window.treeAlpha&&window.treeAlpha.checked&&tree.getAllNodes()[0].expanded;}),true);
 assert.equal(await page.locator('#tree-events').textContent(),'1');
 await page.keyboard.press('ArrowDown');await page.keyboard.press('Space');
 assert.equal(await page.locator('#tree-events').textContent(),'1');
 await page.keyboard.press('ArrowDown');await page.keyboard.press('Space');
 await page.waitForFunction(()=>document.getElementById('tree-events').textContent==='2');
 assert.equal(await page.locator('#tree-model').textContent(),'root,alpha,gamma');
 const treeAX=await cdp.send('Accessibility.getFullAXTree');
 assert.ok(treeAX.nodes.find(n=>n.role?.value==='tree'&&n.name?.value==='Project files'));
 assert.ok(treeAX.nodes.find(n=>n.role?.value==='treeitem'&&n.name?.value==='甲'&&n.properties.some(p=>p.name==='checked'&&p.value.value==='true')));
 await page.waitForFunction(()=>document.getElementById('ssr-accordion-item')?.button);
 assert.equal(await page.locator('#accordion-events').textContent(),'0');
 await page.click('#accordion-update');await page.waitForFunction(()=>document.getElementById('ssr-accordion-item').open);
 await page.waitForFunction(()=>document.getElementById('accordion-events').textContent==='1');
 await page.locator('#ssr-accordion-item button[part=button]').focus();
 await page.evaluate(()=>{window.faqButton=document.getElementById('ssr-accordion-item').button;document.getElementById('accordion-translate').click();});
 await page.waitForFunction(()=>document.getElementById('ssr-accordion-heading').textContent==='常見問題');
 assert.equal(await page.evaluate(()=>document.getElementById('ssr-accordion-item').shadowRoot.activeElement===window.faqButton),true);
 const accordionAX=await cdp.send('Accessibility.getFullAXTree');
 assert.ok(accordionAX.nodes.find(n=>n.role?.value==='heading'&&n.name?.value==='常見問題'&&n.properties.some(p=>p.name==='level'&&p.value.value===2)));
 assert.ok(accordionAX.nodes.find(n=>n.role?.value==='region'&&n.name?.value==='常見問題'));
 await page.keyboard.press('Tab');assert.equal(await page.evaluate(()=>document.activeElement.id),'accordion-content-button');
 await page.evaluate(()=>{document.getElementById('ssr-accordion-item').open=false;});
 await page.waitForFunction(()=>document.getElementById('accordion-model').textContent==='false'&&document.getElementById('accordion-events').textContent==='2');
 assert.equal(await page.evaluate(()=>document.getElementById('ssr-accordion-item').shadowRoot.activeElement===window.faqButton),true);
 await page.evaluate(()=>{const item=document.getElementById('ssr-accordion-item'),parent=item.parentElement;item.remove();parent.append(item);item.button.focus();});
 await page.keyboard.press('Space');await page.waitForFunction(()=>document.getElementById('accordion-model').textContent==='true'&&document.getElementById('accordion-events').textContent==='3');
 assert.equal(await page.evaluate(()=>Object.entries(window.ssrAccordion).every(([id,element])=>element===document.getElementById(id))),true);
 await page.emulateMedia({reducedMotion:'reduce'});
 await page.waitForFunction(()=>document.querySelector('au-carousel')?._dots?.length===2);
 assert.equal(await page.locator('#carousel-events').textContent(),'0');
 await page.click('#carousel-update');await page.waitForFunction(()=>document.querySelector('au-carousel').current===1&&document.getElementById('carousel-events').textContent==='1');
 await page.locator('au-carousel .au-carousel-dot').nth(1).focus();await page.keyboard.press('ArrowLeft');
 await page.waitForFunction(()=>document.getElementById('carousel-model').textContent==='0'&&document.getElementById('carousel-events').textContent==='2');
 await page.evaluate(()=>{window.coastDot=document.querySelector('au-carousel')._dots[0];document.getElementById('carousel-translate').click();});
 await page.waitForFunction(()=>document.querySelector('au-carousel')._dots[0].getAttribute('aria-label')==='海岸, 1 of 2');
 assert.equal(await page.evaluate(()=>document.querySelector('au-carousel').shadowRoot.activeElement===window.coastDot),true);
 const carouselAX=await cdp.send('Accessibility.getFullAXTree');
 assert.ok(carouselAX.nodes.find(n=>n.role?.value==='group'&&n.name?.value==='Destinations'));
 assert.ok(carouselAX.nodes.find(n=>n.role?.value==='button'&&n.name?.value==='海岸, 1 of 2'));
 await page.keyboard.press('Tab');assert.equal(await page.evaluate(()=>document.activeElement.id),'carousel-first-action');
 await page.evaluate(()=>{const c=document.querySelector('au-carousel'),parent=c.parentElement;c.remove();parent.append(c);c._nextBtn.focus();});
 await page.keyboard.press('Enter');await page.waitForFunction(()=>document.getElementById('carousel-events').textContent==='3');
 await page.keyboard.press('Enter');
 assert.equal(await page.locator('#carousel-events').textContent(),'3');
 assert.equal(await page.evaluate(()=>{const c=document.querySelector('au-carousel');return c.current===1&&c.shadowRoot.activeElement===c._nextBtn&&c._nextBtn.getAttribute('aria-disabled')==='true';}),true);
 assert.equal(await page.evaluate(()=>Object.entries(window.ssrSlides).every(([id,element])=>element===document.getElementById(id))),true);
 await page.waitForFunction(()=>document.querySelector('au-card')?.shadowRoot?.querySelector('slot'));
 await page.locator('#card-input').focus();
 await page.locator('#card-input').evaluate(input=>input.setSelectionRange(input.value.length,input.value.length));
 await page.keyboard.press('x');
 await page.evaluate(()=>{window.cardSlot=document.querySelector('au-card').shadowRoot.querySelector('slot[name=content]');document.getElementById('card-translate').click();document.querySelector('au-card').render();});
 await page.waitForFunction(()=>document.getElementById('ssr-card-heading').textContent==='旅遊指南');
 assert.equal(await page.evaluate(()=>document.activeElement.id),'card-input');
 assert.equal(await page.evaluate(()=>document.querySelector('au-card').shadowRoot.querySelector('slot[name=content]')===window.cardSlot),true);
 assert.equal(await page.evaluate(()=>new FormData(document.getElementById('card-form')).get('guide')),'Initialx');
 await page.keyboard.press('Tab');assert.equal(await page.evaluate(()=>document.activeElement.id),'card-action');
 await page.keyboard.press('Space');await page.waitForFunction(()=>document.getElementById('card-actions').textContent==='1');
 const cardAX=await cdp.send('Accessibility.getFullAXTree');
 assert.ok(cardAX.nodes.find(n=>n.role?.value==='heading'&&n.name?.value==='旅遊指南'));
 assert.ok(cardAX.nodes.find(n=>n.role?.value==='textbox'&&n.name?.value==='Guide notes'));
 await page.evaluate(()=>{const c=document.querySelector('au-card'),p=c.parentElement;c.remove();p.append(c);c.render();document.getElementById('card-action').focus();});
 await page.keyboard.press('Enter');await page.waitForFunction(()=>document.getElementById('card-actions').textContent==='2');
 assert.equal(await page.evaluate(()=>Object.entries(window.ssrCard).every(([id,element])=>element===document.getElementById(id))),true);
 await page.waitForFunction(()=>document.querySelector('au-breadcrumbs')?.shadowRoot?.querySelectorAll('a').length===2);
 assert.equal(await page.evaluate(()=>window.ssrCrumbIcon===document.getElementById('ssr-crumb-icon')&&document.querySelector('au-breadcrumbs').shadowRoot.querySelector('slot[name=icon-1]').assignedElements()[0]===window.ssrCrumbIcon),true);
 await page.locator('au-breadcrumbs a').first().focus();await page.keyboard.press('Tab');
 await page.evaluate(()=>{window.crumbLink=document.querySelector('au-breadcrumbs').shadowRoot.activeElement;document.getElementById('crumb-translate').click();});
 await page.waitForFunction(()=>document.querySelector('au-breadcrumbs').items[1].text==='指南');
 assert.equal(await page.evaluate(()=>{const c=document.querySelector('au-breadcrumbs');return c.shadowRoot.activeElement===window.crumbLink&&window.crumbLink.textContent==='指南';}),true);
 const crumbAX=await cdp.send('Accessibility.getFullAXTree');
 assert.ok(crumbAX.nodes.find(n=>n.role?.value==='navigation'&&n.name?.value==='頁面路徑'));
 assert.ok(crumbAX.nodes.find(n=>n.role?.value==='link'&&n.name?.value==='指南'));
 assert.equal(await page.locator('au-breadcrumbs [aria-current=page]').textContent(),'目前頁面');
 await page.keyboard.press('Tab');assert.equal(await page.evaluate(()=>document.activeElement.id),'crumb-translate');
 await page.evaluate(()=>{window.crumbLink.focus();document.getElementById('crumb-shorten').click();});
 await page.waitForFunction(()=>document.querySelector('au-breadcrumbs').items.length===2);
 assert.equal(await page.evaluate(()=>{const c=document.querySelector('au-breadcrumbs');return c.shadowRoot.activeElement===c.shadowRoot.querySelector('nav')&&!window.crumbLink.isConnected;}),true);
 assert.equal(await page.locator('au-breadcrumbs [aria-current=page]').textContent(),'指南');
 assert.equal(await page.locator('au-breadcrumbs a').count(),1);
 await page.locator('au-breadcrumbs a').focus();await page.keyboard.press('Enter');
 await page.waitForURL(url+'/#crumb-home');
 assert.equal(await page.evaluate(()=>document.activeElement.id),'crumb-home');
 assert.equal(await page.evaluate(()=>window.ssrElements['au-breadcrumbs']===document.querySelector('au-breadcrumbs')&&window.ssrCrumbIcon===document.getElementById('ssr-crumb-icon')),true);
 await checkUpload(page,cdp);
 assert.deepEqual(errors,[]);console.log(name,'fifteen components SSR / preserved hosts and reactive node identity / keyboard / events / FormData / AX PASS');await page.close();
}}finally{await browser.close();}
