import assert from 'node:assert/strict';

export async function checkUpload(page, cdp) {
  await page.waitForFunction(()=>!!document.querySelector('au-file-upload')?.fileInput);
  assert.equal(await page.evaluate(()=>Object.entries(window.ssrUpload).length===2&&Object.entries(window.ssrUpload).every(([id,node])=>node===document.getElementById(id))),true);
  const payloads=[{name:'one.txt',mimeType:'text/plain',buffer:Buffer.from('first')},{name:'two.txt',mimeType:'text/plain',buffer:Buffer.from('second')}];
  await page.locator('#ssr-upload-trigger').focus();
  const chooser=page.waitForEvent('filechooser');await page.keyboard.press('Enter');
  await (await chooser).setFiles(payloads);
  await page.waitForFunction(()=>document.getElementById('upload-events').textContent==='1,0');
  assert.equal(await page.locator('#upload-model').textContent(),'one.txt,two.txt');
  assert.deepEqual(await page.evaluate(async()=>Promise.all(new FormData(document.getElementById('upload-form')).getAll('attachments').map(async f=>[f.name,await f.text()]))),[['one.txt','first'],['two.txt','second']]);
  await page.locator('#ssr-upload-trigger').focus();await page.keyboard.press('Tab');
  assert.equal(await page.evaluate(()=>document.querySelector('au-file-upload').shadowRoot.activeElement?._file?.name),'one.txt');
  await page.evaluate(()=>{window.uploadRemove=document.querySelector('au-file-upload').shadowRoot.activeElement;document.getElementById('upload-translate').click();});
  await page.waitForFunction(()=>document.querySelector('au-file-upload').getAttribute('name')==='documents');
  assert.equal(await page.evaluate(()=>document.querySelector('au-file-upload').shadowRoot.activeElement===window.uploadRemove),true);
  const ax=await cdp.send('Accessibility.getFullAXTree');
  assert.ok(ax.nodes.some(n=>n.role?.value==='group'&&n.name?.value==='附件'));
  assert.ok(ax.nodes.some(n=>n.role?.value==='button'&&n.name?.value==='刪除 one.txt'));
  assert.equal(await page.evaluate(()=>new FormData(document.getElementById('upload-form')).has('attachments')),false);
  await page.click('#upload-disable');
  await page.waitForFunction(()=>document.querySelector('au-file-upload').effectiveDisabled);
  assert.deepEqual(await page.evaluate(()=>{const u=document.querySelector('au-file-upload');u.removeFile(u.value[0]);u.handleFiles([new File(['x'],'blocked.txt')]);return [u.value.length,u.fileInput.disabled,new FormData(document.getElementById('upload-form')).has('documents')];}),[2,true,false]);
  await page.click('#upload-disable');await page.waitForFunction(()=>!document.querySelector('au-file-upload').effectiveDisabled);
  assert.equal(await page.locator('#upload-events').textContent(),'1,0');
  await page.locator('au-file-upload button.delete').first().focus();await page.keyboard.press('Space');
  await page.waitForFunction(()=>document.getElementById('upload-events').textContent==='2,1');
  assert.equal(await page.locator('#upload-model').textContent(),'two.txt');
  assert.equal(await page.evaluate(()=>document.querySelector('au-file-upload').shadowRoot.activeElement?._file?.name),'two.txt');
  await page.keyboard.press('Enter');await page.waitForFunction(()=>document.getElementById('upload-events').textContent==='3,2');
  assert.equal(await page.evaluate(()=>document.activeElement.id),'ssr-upload-trigger');
  assert.equal(await page.evaluate(()=>document.getElementById('upload-form').reportValidity()),false);
  assert.equal(await page.locator('au-file-upload .error-list').textContent(),'Please select at least one file.');
  assert.equal(await page.evaluate(()=>document.querySelector('au-file-upload').shadowRoot.activeElement===document.querySelector('au-file-upload').triggerArea),true);
  await page.locator('#ssr-upload-trigger').focus();
  const second=page.waitForEvent('filechooser');await page.keyboard.press('Space');await (await second).setFiles(payloads.slice(0,1));
  await page.waitForFunction(()=>document.getElementById('upload-events').textContent==='4,2');
  await page.click('#upload-reset');
  await page.waitForFunction(()=>document.getElementById('upload-model').textContent==='');
  assert.equal(await page.locator('#upload-model').textContent(),'');
  assert.deepEqual(await page.evaluate(()=>[document.querySelector('au-file-upload').value.length,[...new FormData(document.getElementById('upload-form'))].length]),[0,0]);
  await page.evaluate(()=>{const u=document.querySelector('au-file-upload'),p=u.parentElement;u.remove();p.append(u);u.value=[new File(['controlled'],'controlled.txt')];});
  assert.equal(await page.locator('#upload-events').textContent(),'4,2');
  assert.equal(await page.evaluate(async()=>new FormData(document.getElementById('upload-form')).get('documents').text()),'controlled');
  await page.locator('au-file-upload button.delete').focus();await page.keyboard.press('Enter');
  await page.waitForFunction(()=>document.getElementById('upload-events').textContent==='5,3');
  assert.equal(await page.evaluate(()=>Object.entries(window.ssrUpload).every(([id,node])=>node===document.getElementById(id))),true);
}
