<script setup>
const uploadName=ref('attachments'),uploadLabel=ref('Attachments'),removeLabel=ref('Remove'),uploadDisabled=ref(false),uploadEvents=ref(0),uploadRemoved=ref(0),uploadModel=ref('');
const value=ref(1),name=ref('review'),count=ref(0),ready=ref(false);
const accordionOpen=ref(false),accordionLabel=ref('FAQ'),accordionEvents=ref(0);
const cardLabel=ref('Travel guide'),cardActions=ref(0);
const crumbLabel=ref('Page trail'),crumbs=ref([{text:'Home',url:'#crumb-home'},{text:'Guides',url:'#crumb-guides'},{text:'Current page'}]);
const carouselIndex=ref(0),carouselEvents=ref(0),carouselTitle=ref('Coast');
const text=ref('Initial'),inputs=ref(0);
const notes=ref('Initial notes'),notesEvents=ref(0);
const choice=ref(false),enabled=ref(false),toggleEvents=ref(0);
const delivery=ref('standard'),radioEvents=ref(0),radioLabel=ref('Express'),radioDisabled=ref(false);
const tabIndex=ref(1),tabEvents=ref(0),tabLabel=ref('Details');
const page=ref(2),pageSize=ref(10),pageEvents=ref(0),sizeEvents=ref(0),nextLabel=ref('Next');
const menuLabel=ref('Document actions'),actionLabel=ref('Save'),actionValue=ref('save'),action=ref(''),actionEvents=ref(0);
const treeData=ref([{id:'root',label:'Files',children:[{id:'alpha',label:'Alpha'},{id:'beta',label:'Beta',disabled:true},{id:'gamma',label:'Gamma'}]}]),treeChecks=ref(''),treeEvents=ref(0);
onMounted(()=>{ready.value=true;});
function changed(event){value.value=event.detail.value;count.value++;}
</script>
<template><main><h1>Nuxt component SSR</h1>
<form id="upload-form" enctype="multipart/form-data" @reset="uploadModel=''"><fieldset id="upload-fieldset" :disabled="uploadDisabled"><legend>File attachments</legend><au-file-upload :name="uploadName" :label="uploadLabel" :msg-remove-text="removeLabel" multiple required accept=".txt" @change="uploadModel=$event.target.value.map(f=>f.name).join(',');uploadEvents++" @remove-file="uploadRemoved++"><button id="ssr-upload-trigger" type="button" slot="trigger">Choose attachments</button><span id="ssr-upload-hint" slot="hint">Text files only</span></au-file-upload></fieldset><button id="upload-reset" type="reset">Reset attachments</button></form>
<button id="upload-translate" @click="uploadLabel='附件';removeLabel='刪除';uploadName='documents'">Translate attachments</button><button id="upload-disable" @click="uploadDisabled=!uploadDisabled">Toggle uploads</button><output id="upload-model">{{uploadModel}}</output><output id="upload-events">{{uploadEvents}},{{uploadRemoved}}</output>
<span id="crumb-label">{{crumbLabel}}</span><au-breadcrumbs aria-labelledby="crumb-label" :items.attr="JSON.stringify(crumbs)"><span id="ssr-crumb-icon" slot="icon-1" aria-hidden="true">⌂</span></au-breadcrumbs>
<button id="crumb-translate" @click="crumbLabel='頁面路徑';crumbs=[{text:'首頁',url:'#crumb-home'},{text:'指南',url:'#crumb-guides'},{text:'目前頁面'}]">Translate trail</button>
<button id="crumb-shorten" @click="crumbs=[{text:'首頁',url:'#crumb-home'},{text:'指南'}]">Shorten trail</button><h2 id="crumb-home" tabindex="-1">Home destination</h2><h2 id="crumb-guides" tabindex="-1">Guides destination</h2>
<form id="card-form"><au-card><div id="ssr-card-footer" slot="footer"><button type="button" id="card-action" @click="cardActions++">Save guide</button></div><div id="ssr-card-content" slot="content"><label for="card-input">Guide notes</label><input id="card-input" name="guide" value="Initial"></div><h2 id="ssr-card-heading" slot="heading">{{cardLabel}}</h2></au-card></form>
<button id="card-translate" @click="cardLabel='旅遊指南'">Translate card</button><output id="card-actions">{{cardActions}}</output>
<au-carousel :current.prop="carouselIndex" aria-label="Destinations" @slide-change="carouselIndex=$event.detail.index;carouselEvents++"><article id="ssr-slide-first" :data-title="carouselTitle"><button id="carousel-first-action">Coast guide</button></article><article id="ssr-slide-second" data-title="City"><button>City guide</button></article></au-carousel>
<button id="carousel-update" @click="carouselIndex=1">City</button><button id="carousel-translate" @click="carouselTitle='海岸'">Translate destination</button><output id="carousel-model">{{carouselIndex}}</output><output id="carousel-events">{{carouselEvents}}</output>
<au-accordion><au-accordion-item id="ssr-accordion-item" heading-level="2" :open.attr="accordionOpen ? '' : null" @au-toggle="accordionOpen=$event.detail.open;accordionEvents++"><span id="ssr-accordion-heading" slot="heading">{{accordionLabel}}</span><div id="ssr-accordion-content" slot="content"><button id="accordion-content-button">Read answer</button></div></au-accordion-item></au-accordion>
<button id="accordion-update" @click="accordionOpen=true">Open FAQ</button><button id="accordion-translate" @click="accordionLabel='常見問題'">Translate FAQ</button><output id="accordion-model">{{accordionOpen}}</output><output id="accordion-events">{{accordionEvents}}</output>
<span id="tree-label">Project files</span><au-tree :data.prop="treeData" show-checkbox aria-labelledby="tree-label" @change="treeChecks=$event.detail.checkedNodes.map(n=>n.id).join(',');treeEvents++" />
<button id="tree-translate" @click="treeData=[{id:'root',label:'檔案',children:[{id:'alpha',label:'甲',lang:'zh-Hant'},{id:'beta',label:'Beta',disabled:true},{id:'gamma',label:'Gamma'}]}]">Translate tree</button><output id="tree-model">{{treeChecks}}</output><output id="tree-events">{{treeEvents}}</output>
<au-dropdown :data-text-trigger="menuLabel" @selected="action=$event.detail.value;actionEvents++"><au-dropdown-item id="ssr-action-edit" value="edit">Edit</au-dropdown-item><au-dropdown-item id="ssr-action-save" :value="actionValue">{{actionLabel}}</au-dropdown-item></au-dropdown>
<button id="action-translate" @click="menuLabel='文件操作';actionLabel='儲存';actionValue='save-copy'">Translate actions</button><output id="action-model">{{action}}</output><output id="action-events">{{actionEvents}}</output>
<au-pagination data-total="100" :data-current-page="page" :data-page-size="pageSize" :data-text-next="nextLabel" @page-change="page=$event.detail;pageEvents++" @page-size-change="pageSize=$event.detail;page=1;sizeEvents++" />
<button id="page-update" @click="page=4">Page four</button><button id="page-label-update" @click="nextLabel='下一頁'">Translate navigation</button><output id="page-model">{{page}},{{pageSize}}</output><output id="page-events">{{pageEvents}},{{sizeEvents}}</output>
<span id="sections-label">Review sections</span><au-tabs :selected-index="tabIndex" aria-labelledby="sections-label" @tab-change="tabIndex=$event.detail.index;tabEvents++"><section id="ssr-panel-first" class="au-tab-panel" slot="panel" label="Overview">Overview content</section><section id="ssr-panel-second" class="au-tab-panel" slot="panel" :label="tabLabel" :label-lang="tabLabel==='Details'?'en':'zh-Hant'">Details content</section></au-tabs>
<button id="tab-label-update" @click="tabLabel='細節'">Translate tab</button><button id="tab-update" @click="tabIndex=1">Details tab</button><output id="tab-events">{{tabEvents}}</output><output id="tab-model">{{tabIndex}}</output>
<form id="controls-form"><au-rating :name="name" :value="value" aria-label="Review rating" labels="Bad,Fair,Good,Great,Excellent" @change="changed" />
<span id="text-label">Review text</span><span id="text-help">Enter a review</span><au-input :value="text" name="text" aria-labelledby="text-label" aria-describedby="text-help" @input="text=$event.target.value;inputs++" />
<span id="notes-label">Review notes</span><span id="notes-help">Enter detailed notes</span><au-textarea :value="notes" name="notes" aria-labelledby="notes-label" aria-describedby="notes-help" @input="notes=$event.target.value;notesEvents++" />
<span id="choice-label">Receive news</span><span id="toggle-help">Optional preference</span><au-checkbox name="choice" :checked="choice" aria-labelledby="choice-label" aria-describedby="toggle-help" @change="choice=$event.detail;toggleEvents++" />
<span id="enabled-label">Enable notifications</span><au-switch name="enabled" :checked="enabled" aria-labelledby="enabled-label" aria-describedby="toggle-help" @change="enabled=$event.detail;toggleEvents++" />
<span id="delivery-label">Delivery</span><span id="delivery-help">Choose one delivery option</span><au-radio-group name="delivery" :value="delivery" :disabled="radioDisabled" aria-labelledby="delivery-label" aria-describedby="delivery-help" @change="delivery=$event.detail.value;radioEvents++"><au-radio value="standard" checked>Standard</au-radio><au-radio value="express" :label="radioLabel">Express</au-radio><au-radio value="unavailable" disabled>Unavailable</au-radio></au-radio-group></form>
<button id="radio-update" @click="delivery='express'">Express delivery</button><button id="radio-label-update" @click="radioLabel='快遞'">Translate option</button><button id="radio-disable" @click="radioDisabled=!radioDisabled">Toggle availability</button><output id="radio-events">{{radioEvents}}</output><output id="radio-model">{{delivery}}</output>
<button id="toggle-update" @click="choice=true;enabled=true">Enable both</button><output id="toggle-events">{{toggleEvents}}</output><output id="toggle-model">{{choice}},{{enabled}}</output>
<button id="update" @click="value=4;name='updated';text='Changed';notes='Changed notes'">Update values</button><output id="events">{{count}}</output><output id="input-events">{{inputs}}</output><output id="notes-events">{{notesEvents}}</output><output id="notes-model">{{notes}}</output><output id="ready">{{ready}}</output></main></template>
